name: Build Preview APK
on: [push]
jobs:
    build-apk:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node v20
              uses: actions/setup-node@v4.0.1
              with:
                  node-version: '20.x'

            - name: Enable Corepack to use Yarn
              run: corepack enable

            - name: Yarn Install
              run: yarn
