name: build-preview-apk
on: [push]
jobs:
    build-apk:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node v20
              uses: actions/setup-node@v4.0.1
              with:
                  node-version: '20.x'

            - name: Set Yarn Version to 4.0.2
              uses: borales/actions-yarn@v4
              with:
                  cmd: set version 4.0.2

            - name: Yarn Install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            - name: Build Preview APK
              uses: borales/actions-yarn@v4
              with:
                  cmd: build:dev
