name: Build Preview APK
on: [push]
jobs:
    build-apk:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node v20
              uses: actions/setup-node@v4.0.1
              with:
                  node-version: '20.x'

            - name: Enable Corepack to use Yarn
              run: corepack enable

            - name: Setup Expo and EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: '7.0.0'
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: Yarn Install
              run: yarn

            - name: Build on EAS
              run: eas build -p android --profile preview --non-interactive --no-wait
